# Generated by Django 6.0.3 on 2026-04-01 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_nom', models.CharField(max_length=120)),
                ('participant_prenom', models.CharField(max_length=120)),
                ('participant_date', models.DateField(blank=True, null=True)),
                ('score20', models.FloatField(blank=True, null=True)),
                ('stats', models.JSONField(default=dict)),
                ('qcm_results', models.JSONField(default=list)),
                ('free_results', models.JSONField(default=list)),
                ('pdf_payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
